### ISSUE TITLE
Supports image used by ARM64 arch

### ISSUE THREAD

**Issue by xichengliudui** [rabbitmq/cluster-operator#1052]
**Is your feature request related to a problem? Please describe.**

rabbitmq operator does not currently run on ARM64 arch machines, i want to be able to run operator on the ARM64 arch

**Describe the solution you'd like**

build image for the ARM64 arch
looking forward to any reply, ref: https://github.com/rabbitmq/cluster-operator/issues/366

**Comment by Zerpet** [comment]
Thank you for rising this issue. We do see value in providing an arm64 image. We have to do some exploration on how to achieve this. Our main challenge may be that we don't have arm64 infrastructure to run and validate the OCI. I will have a look at this in the coming days.

**Comment by xichengliudui** [comment]
> Thank you for rising this issue. We do see value in providing an arm64 image. We have to do some exploration on how to achieve this. Our main challenge may be that we don't have arm64 infrastructure to run and validate the OCI. I will have a look at this in the coming days.

thanks！

**Comment by Zerpet** [comment]
I've been experimenting on this for a couple of days, here are my conclusions and what to do next:

Building multi platform images is possible thanks to [docker buildx](https://docs.docker.com/buildx/working-with-buildx/). Other container technologies, like containerd and `nerdctl`, can also leverage `buildx` via [moby/buildkit](https://github.com/moby/buildkit/blob/master/docs/multi-platform.md) and produce multi platform images.

It is important to note that multi platform images provide multiple, platform-specific, images under the same **name and tag**. What does this mean? It means that we can produce a images for `amd64` and `arm64`, both under `rabbitmqoperator/cluster-operator:latest`, or any other tag. The container runtime does the right thing when you pull and/or run an image, and it pulls the image that matches your platform automagically.

Whilst it is possible to do this locally, we want to incorporate this enhancement in our CI/CD pipelines. We currently use Concourse and `concourse/oci-build-task`. It looks like this task has a limitation and it is not capable of building multi platform images, as reported in concourse/oci-build-task/issues/85

This limitation is quite tragic, because we will have to either fix the build task in the upstream, or move the image building process somehwere else, like GitHub Action with a [supported multi platform image builder](https://github.com/marketplace/actions/build-and-push-docker-images).

**Comment by ablease** [comment]
Closing this since Tanzu Net does not support multi arch images :(

**Comment by bigbitbus** [comment]
A lot of devs have M1 Arm64 machines now, not having a Arm64 docker image for Rabbitmq shuts them out from Rabbitmq.

**Comment by Zerpet** [comment]
[RabbitMQ official image][rmq] has support for ARM processors, and the Cluster Operator also has multi-arch support:

https://github.com/rabbitmq/cluster-operator/blob/f9be07b592a2167db01550e97014b56b29e70d63/.github/workflows/build-test-publish.yml#L106-L110

You can verify this information pulling the latest image and running:

```bash
docker buildx imagetools inspect rabbitmqoperator/cluster-operator:latest
# Name:      docker.io/rabbitmqoperator/cluster-operator:latest
# MediaType: application/vnd.docker.distribution.manifest.list.v2+json
# Digest:    sha256:563f230500a3efb1a90ae52b3090cd9f20c5c08d57ff063ec7ce88fbb0b1ab4c
# 
# Manifests:
#   Name:      docker.io/rabbitmqoperator/cluster-operator:latest@sha256:68e4cfb3043a5f4b8cec9df4c482eda7c43995db76082fbdddf3a16969e39eba
#   MediaType: application/vnd.docker.distribution.manifest.v2+json
#   Platform:  linux/amd64
# 
#   Name:      docker.io/rabbitmqoperator/cluster-operator:latest@sha256:71b848a53f2c4f166b26c645286177a59d78da5e26ad13a0f61d11ebb34bf0a5
#   MediaType: application/vnd.docker.distribution.manifest.v2+json
#   Platform:  linux/arm64
```

[rmq]: https://hub.docker.com/_/rabbitmq
