### ISSUE TITLE
Quorum queues create with only 1 member when using definition file

### ISSUE THREAD

**Issue by Shahzad24** [rabbitmq/cluster-operator#1123]
When using definition file to create Quorum queues on 3 or more node rabbit cluster, the Queue only get 1 member with no redundancy. If quorum queues are created after a 3 node RabbitMQ cluster  is created, the queues get 3 members and function normal. How can we use definition file to create quorum queues with 3 members. Is it possible to add a delay in the definition import so that import happens after the 3 node cluster setup is complete ?

**Comment by mkuratczyk** [comment]
Set `cluster_formation.target_cluster_size_hint = 3` in the configuration. When you do, all but the last node to start will skip queue/binding import, so the definitions will be imported just once, when all nodes are present.
https://github.com/rabbitmq/rabbitmq-server/pull/3981

**Comment by mkuratczyk** [comment]
Sorry, I didn't notice you asked in the cluster-operator repo, not the rabbitmq-server repo. The answer still stands, but for completeness, this setting has been added recently and will be set by default in the next release: https://github.com/rabbitmq/cluster-operator/pull/1113

We could not use it earlier since the cluster operator supported RabbitMQ versions that didn't have this setting (and would fail to start if it was set in the config file). But you don't have to wait for the next cluster-operator release - you can just add it to your `spec.rabbitmq.additionalConfig` right now, if you are running a sufficiently recent version of RabbitMQ (3.8.24+, 3.9.9+ or 3.10).

**Comment by Shahzad24** [comment]
Hi Michal, thanks for the response, that is exactly what I needed and it works great now.
