### ISSUE TITLE
how to configure the mqtt attribute with advancedConfiguration

### ISSUE THREAD

**Issue by janiu-001** [rabbitmq/cluster-operator#1196]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/19970581/203015863-c5de0bd1-2636-44cb-be7e-4edc65316056.png">

I tried to configure the mqtt(above field) with the following format, but it could not work

[
    {rabbit,
      [
        {vm_memory_high_watermark, 0.9}
      ]
    },
    {rabbitmq_mqtt,
      [
        {ssl_listeners, 8883},
        {tcp_listeners, 1883}
      ]
    }
  ].

Would you help to share you suggestions?

**Comment by DanielePalaia** [comment]
HI @janiu-001 I discussed this internally with the team. We noticed that you already posted few other questions on this topic. Usually we are happy to provide support to users but when opening a request to support please open a new discussion or if you think is a bug please specify detailed informations on the Issue you are having like: full description of the issue (the issue is when starting the operator? the pod are correctly starting? what kind of testing you are doing?), logs whenever possibile / versions of the operator/rabbitmq you are using ecc...
