### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by egeneralov** [rabbitmq/cluster-operator#1202]
M1 has been around for a long time, Ampere Altra is taking over the server world. Builds under Arm64 would be extremely useful (the rabbitmq itself supports).

You can find an example of solving the assembly problem [here](https://github.com/egeneralov/cluster-operator/compare/main...egeneralov:cluster-operator:arm#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05ada)

**Comment by coro** [comment]
Hi @egeneralov, we absolutely agree, multiarch builds of all the operators would be fantastic and is definitely something we want to have. We've been hesitant to move forwards due to some of our internal tooling not yet supporting multiarch OCIs, however we could have a workaround whereby we separately build a single-arch OCI for that tooling, and release muti-arch OCIs everywhere else. I will raise this again with the team.
