### ISSUE TITLE
Prometheus is unable to scrape metrics from the RabbitMQ Cluster Operator

### ISSUE THREAD

**Issue by slgray** [rabbitmq/cluster-operator#1431]
Describe the bug:
Prometheus is unable to scrape metrics from the RabbitMQ Cluster Operator when using the provided `observability/prometheus/config-file.yml` configuration. The inconsistency in the component label could be a potential cause.

Expected behavior:
Prometheus should successfully scrape metrics from the RabbitMQ Cluster Operator.

Additional context:
The inconsistency in the label app.kubernetes.io/component (`rabbitmq-cluster-operator` vs `rabbitmq-operator`) might be causing Prometheus to look for the wrong target.

**Comment by ikvmw** [comment]
Hi, thank you for the report. Just to make things extra clear, could you please share the following:

1. Operator Version
2. Prometheus Version
4. Your installation steps - how can I reproduce?

Cheers

**Comment by slgray** [comment]
1. Operator Version: rabbitmqoperator/cluster-operator:2.2.0
2.Prometheus Version: I use Azure Monitor managed service for Prometheus, which do not

**Comment by ikvmw** [comment]
yeah that's interesting because when I deploy it at least here in KIND Prom target is green without any component name changes.   But I was using HEAD, let me try 2.2.0

**Comment by ikvmw** [comment]
So Operator itself is monitored via PodMonitor: https://github.com/rabbitmq/cluster-operator/blob/v2.2.0/observability/prometheus/monitors/rabbitmq-cluster-operator-podmonitor.yml which has correct component label and that's why it shows on Service Discovery page of Prometheus. 

The line you referring to merely drops that label if value doesn't much. Which could be a reason it's not seen in say grafana, if dashboards rely on it (I'll check).

But Prometheus should be able to use PodMonitor.

**Comment by slgray** [comment]
The file you provide is monitor with Prometheus Operator, [ Monitor RabbitMQ Without Prometheus Operator ](https://www.rabbitmq.com/kubernetes/operator/operator-monitoring.html#prom-annotations) is be configured via a config file according the document.
