### ISSUE TITLE
ArgoCD supporting RabbitMQCluster CR

### ISSUE THREAD

**Issue by aaguilartablada** [rabbitmq/cluster-operator#1437]
Hello!

I have contributed to ArgoCD project in order to support checking health status for RabbitMQCluster resources managed by this operator. You can see the PR here: https://github.com/argoproj/argo-cd/pull/15286

Could you please review it in order to check I am forgetting nothing? Thanks!

**Comment by 3deep5me** [comment]
Hello!
I would like to join a question here since it is also about the operator in combination with ArgoCD.
Does anyone know if it is somehow possible to set password and user with a secretRef similar to rabbitmq [bitnami helmchart](https://github.com/bitnami/charts/blob/2e2a7d1ba7c9691eca4bbb7f07059be5c9a7c11a/bitnami/rabbitmq/values.yaml#L147)?

In a GitOps scenario it is unsafe to use the [example implementation](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/set-login-password-username).

@aaguilartablada How do you face this difficulty?

**Comment by 3deep5me** [comment]
Never mind found this:
https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/external-admin-secret-credentials
