### ISSUE TITLE
Option to monitor multiple namespaces (but not all)

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#166]
We currently support cluster-scoped deployments or single-namespace deployments. Seems like there is an easy way to also allow multiple namespaces as discussed here:
https://vmware.slack.com/archives/CJWJ6U9GR/p1592479357329500

Given that it's relatively straightforward, we can add this option for completeness.

**Comment by j4mcs** [comment]
Copying from a duplicate issue:

We [added](https://github.com/rabbitmq/cluster-operator/commit/5ed8e6f4aaf9e80129fc62a257080cb7998dd0f7) the ability to constrain the operator to a single namespace by setting an environment variable. However, we don't provide the resource yaml to reflect this i.e. deploy a role and rolebinding instead of a clusterrole and clusterrole binding. We also currently lack a make target to switch to this type of deployment.

**Describe the solution you'd like**
Add a kustomize overlay for single namespace deploys 

**Describe alternatives you've considered**
We could use a [multinamespaceCacheBuilder](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/cache#MultiNamespacedCacheBuilder) when initialising the manger:
```
    var namespaces []string // List of Namespaces

    mgr, err = ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
        Scheme:             scheme,
        NewCache:           cache.MultiNamespacedCacheBuilder(namespaces),
        MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
    })
```

This will likely be explored as a feature in future but we don't currently have a requirement for a shortlist of namespaces

**Comment by Mercanuis** [comment]
I would like to know an update on this issue, if at all. Can the Rabbit Operator monitor cluster deployments in multiple namespaces or is it limited to the scope of the namespace the operator is deployed?

**Comment by Zerpet** [comment]
The Operator monitors all namespaces by default. You can limit to a single namespace by setting an environment variable with name `OPERATOR_SCOPE_NAMESPACE` in the Operator deployment.

**Comment by Mercanuis** [comment]
> The Operator monitors all namespaces by default. You can limit to a single namespace by setting an environment variable with name `OPERATOR_SCOPE_NAMESPACE` in the Operator deployment.

Thank you for letting me know. I wasn't sure because of the documentation provided, it seems the topology operator suggests it but prior issues on this repo as well as the main documentation on the cluster operator don't make it explicit. I might suggest kindly that somewhere that the default behavior is called out.
