### ISSUE TITLE
Explore and propose a release and versioning strategy

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#190]
## Why 

Our current versioning strategy creates a release for every commit in master. This was a good strategy when we were releasing through TanzuNet and wanted to have the ability to promote a build from "the past" into a release candidate.

Given that we won't publish artefacts anymore to TanzuNet, we should re-think our release strategy and versioning. This issue will cover the exploration and write up of a proposal.

## Questions to explore

- Use [semver](https://semver.org/) for version numbers. Do we want to keep the same versioning?
- Publish every build or cut specific releases?
- Publish docker images as part of the release?
- Where to publish release artefacts?

Further considerations if/assuming we pick SemVer:

- Supportability of major and minor versions. For how long can/should we support a minor? For how long can/should we support a major?

The **outcome** of this issue should be a KEP or proposal document.

**Comment by Zerpet** [comment]
References:
- [Python PEP 440](https://www.python.org/dev/peps/pep-0440/#)
- [SemVer](https://semver.org/)
- [CalVer](https://calver.org/)
- [Changing the API, Kubernetes community](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md)

**Comment by Zerpet** [comment]
## Idea 💡

We would like to get the following out of our versioning strategy:

- Clarity on compatibility. We understand compatibility as described in [Kubernetes Architecture guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md)
- Clarity on supportability. Anybody who wishes to offer commercial support for this, should be able to easily determine when a version was released and for how long to offer support.
- Flexibility for us to deliver new versions/fixes in a timely fashion.

Given those requirements, I'm considering the following versioning scheme:

```
vN[beta|alpha].YYYY.MM.N
```

- Where `N` is a non-negative integer, including 0.
- Where `YYYY` is a year in 4 digit format e.g. 2020
- Where `MM` is a month digit e.g. 1 for January, 2 for February, etc.

The first segment of the version will be the prefered version (meaning of "prefered" in [Kubernetes Deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/)). We will follow the deprecation policy specified by Kubernetes. It may include the "alpha" or "beta" wording to indicate the state of the API, according to Kuberntes. The "alpha" or "beta" shall not include a suffix number.

The second segment is a CalVer segment with the year and month. We intend to make it very clear when a version was released and it will make it very easy if a version is supported (pending to define a support policy).

The last segment is a number, indicating a patch or micro version. This is intended to allow us to backport certain CVEs or critical fixes.

**Comment by michaelklishin** [comment]
If you go with SemVer and only bump majors (or, like Kubernetes has been doing recently, only bump minors) and provide a release date and support schedule visibly in the docs and GitHub releases, would this proposed scheme be different?

I understand and agree with the premise but it is a highly unusual versioning scheme. As much as I dislike strict SemVer, a lot of tooling and folks in the industry understand how it works.

**Comment by coro** [comment]
To add my two cents, I think that compatibility considerations of our versioning should not just focus on Kubernetes API compatibility. There are multiple dimensions of compatibility to which versions of the operator adhere; a new version may support:

- A subset of Kubernetes API versions for the CR, of which one is the 'preferred' version according to the [Kubernetes Deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/)
- A subset of Kubernetes server versions (e.g. right now, 1.15-1.17)
- A subset of RabbitMQ Server versions (e.g. right now, 3.8.x and onwards)

A change in support for any of these could be enough to warrant a new version of the operator, and it should be clear when such a change occurs, either through the versioning syntax we use or documentation. An example is the FDB operator, which has a [template compatibility matrix](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/compatibility.md) which demonstrates what that support may look like.

One thing I find odd is the use of the preferred API version in the operator version - given the Kubernetes Deprecation Policy Rule #4b, the latest API version for the CR is only 'preferred' once it has been released for its second release. Following the proposal above, that would mean if a user wanted to get their hands on some exciting v2 API features, the first release they would use would be v1.2020.MM.0, rather than anything starting with v2, which feels confusing to me.
