### ISSUE TITLE
Using RabbitMQ Cluster Kubernetes Operator step by step but failed to get pod ready

### ISSUE THREAD

**Issue by Darwinarch** [rabbitmq/cluster-operator#269]
## Describe the bug
Hi, 
      When I followed [the instruction online](https://www.rabbitmq.com/kubernetes/operator/using-operator.html) step by step, I could not make the pods ready !
![11](https://user-images.githubusercontent.com/69334027/91129026-ddb3dd00-e6db-11ea-9a6d-7b435a495da7.jpg)
      After I described the pod, 
      `kubectl describe po definition-rabbitmq-server-0`  
      I got the following message :
![22](https://user-images.githubusercontent.com/69334027/91129743-1a340880-e6dd-11ea-8767-6992c0134656.jpg)
       and the log told me that :
![66](https://user-images.githubusercontent.com/69334027/91150555-1e692180-e6ef-11ea-853c-52bca7c5fbba.jpg)
      my definition.yaml :
![33](https://user-images.githubusercontent.com/69334027/91130116-ba8a2d00-e6dd-11ea-87de-778c6458329e.jpg)
      my cluster info : only devd02 has PV
![55](https://user-images.githubusercontent.com/69334027/91130935-07bace80-e6df-11ea-98ca-f7efa85e87ea.jpg)
       
     I don't know what's wrong in my setup and I need some help.  Thanks a lot !

**Comment by ansd** [comment]
Hey @Darwinarch,

thanks for reaching out and for the detailed screenshots.

Did you create the file `rabbitmq-headless.yml` manually?
The selector `app: rabbitmq` looks suspicious therein.

What should happen instead is that the cluster operator creates a headless service (namely the `service/definition-rabbitmq-headless` output in your first screenshot) adding a label `app.kubernetes.io/name: definition` to it.

**Comment by Darwinarch** [comment]
Hello @ansd  ,

I didn't create the rabbitmq-headless.yaml by myself. 
Should I create it according to [here](https://www.rabbitmq.com/blog/2020/08/10/deploying-rabbitmq-to-kubernetes-whats-involved/) ?

In addition, `service/definition-rabbitmq-headless` is generated automatically after I key in `kubectl apply -f definition.yaml`.
When I described `definition-rabbitmq-headless`, `app.kubernetes.io/name: definition` had been labeled as follow:
![1](https://user-images.githubusercontent.com/69334027/91250219-0f37b180-e78b-11ea-9539-fdf2a08ad8af.jpg)

The difference between `definition-rabbitmq-headless` and [example headless-service.yaml](https://github.com/rabbitmq/diy-kubernetes-examples/blob/master/gke/headless-service.yaml) seems like missing to asign port=25672 for cluster-links
![2](https://user-images.githubusercontent.com/69334027/91250695-3a6ed080-e78c-11ea-9316-f9f3b8cd4f4f.jpg)

Does that setting lead to the pods not ready in my cluster ? And how do I fix it before the `service/definition-rabbitmq-headless` automatically be started ?

**Comment by ansd** [comment]
> Should I create it according to here ?

No, you shouldn't.

The missing cluster-links port in the headless service is a good catch.
I'm not sure why we didn't include it.
As you correctly pointed out, it is defined in the [examples](https://github.com/rabbitmq/diy-kubernetes-examples/blob/e1b54b79566cd3ecc3050c4695a9cc70b063676e/gke/headless-service.yaml#L13-L16), but not in the operator https://github.com/rabbitmq/cluster-operator/blob/6045ea9ae99c689c62eba2042d7804f96944394f/internal/resource/headless_service.go#L51-L62

You can try to add this port to the operator, and to build and deploy the operator image as describe in the README and see whether this fixes your issue?

What IaaS does your Kubernetes cluster run on?
What Kubernetes version are you using?

The error message in your screenshot outputs `nxdomain (non-existing domain)` for the host `definition-rabbitmq-server-0.definition-rabbitmq-headless.default`.

What does nslookup return in this container?
Since I assume that you use a dev environment, what you can try out is to deploy a RabbitMQ instance with the following `override`:
```
spec:
  ...
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              securityContext:
               runAsUser: 0
```
This allows you to troubleshoot as root user in your container:
```
kubectl exec pod/definition-rabbitmq-server-0 -ti  -- /bin/bash

# apt update && apt install -y dnsutils
# nslookup definition-rabbitmq-server-0.definition-rabbitmq-headless.default
```

**Comment by Darwinarch** [comment]
Hello @ansd ,

Thanks a lot ! 

Although I overrode what you mentioned above in my definition.yaml,  the 
`pod/definition-rabbitmq-server-0`  rebooted over and over again so that 
"`kubectl exec pod/definition-rabbitmq-server-0 -ti  -- /bin/bash`" was not working !

My cluster info is described as follow :
![3](https://user-images.githubusercontent.com/69334027/91372912-86cb1680-e847-11ea-8bc4-579fd57ad266.jpg)

And I followed  [the instruction online](https://www.rabbitmq.com/kubernetes/operator/operator-overview.html) step by step on my docker-desktop yesterday, everything is ok !
![1](https://user-images.githubusercontent.com/69334027/91373001-d0b3fc80-e847-11ea-8945-84d48bdd7575.jpg)

but the kubernetes on 【docker-desktop is 1.16.5】 and 【my cluster is 1.18.8】
![2](https://user-images.githubusercontent.com/69334027/91373052-00630480-e848-11ea-9148-bff7478fc76f.jpg)
 
FYI

Sincerely

**Comment by ChunyiLyu** [comment]
Hi @Darwinarch 

I just tested our operator on a local KinD cluster with k8s `v1.18.8` and it's working. 

Could you let us know how you provisioned your kubernetes cluster? It's puzzling to me that the k8s version shown in your docker desktop screen shot is `1.16.5`, whereas the k8s version shown from your `kubectl version` is `1.18.8`.

I suspect that the failure you are getting is due to some domain/dns setup in your cluster, which is hard for me to debug without knowing how your k8s cluster is provisioned and setup. If you don't have a specific requirement on your k8s environment, I would recommend trying the operator out in [a local kinD cluster](https://kind.sigs.k8s.io/docs/user/quick-start/) version `1.16` or above, since that's the setup the team uses and tests on everyday. Thanks!

**Comment by Gsantomaggio** [comment]
[In additional]
@ansd you can debug the DNS problems by following [this guide](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)


using the dns pod:
```
kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
```

Then execute the nslookup:
```
kubectl exec -i -t dnsutils -- nslookup  definition-rabbitmq-server-0.definition-rabbitmq-headless.default
```

and the result should be something like:
```
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   definition-rabbitmq-server-0.definition-rabbitmq-headless.default.svc.cluster.local
Address: 10.244.0.7
```


Also check the `kubernetes` dns:
```
 kubectl exec -i -t dnsutils -- nslookup  kubernetes.default
```
result:
```
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.96.0.1
```

If it does not work, you should check the coredns configuration:
```
 forward . /etc/resolv.conf
        cache 30
```
And execute the [dns test](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#check-the-local-dns-configuration-first)

you should have, something like:
```
kubectl exec -ti dnsutils -- cat /etc/resolv.conf
```
result:
```
search default.svc.cluster.local svc.cluster.local cluster.local lan
nameserver 10.96.0.10
```

**Comment by Gsantomaggio** [comment]
I would close this issue, I don't think it is a bug cc @ChunyiLyu @ansd
