### ISSUE TITLE
Use maintenance mode for termination

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#320]
**Is your feature request related to a problem? Please describe.**
rabbitmq `3.8.8` ships with a newly added maintenance mode. It makes senses for us to use it before shutting down pods for upgrade, or even before any kind of pod restart.

Is this something we only need to run before during upgrade? Should we run it in `preStop` hook for any pod termination?

[Maintenance mode feature PR](https://github.com/rabbitmq/rabbitmq-server/issues/2321)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zerpet** [comment]
When Michael introduced this feature to our team, I remember him mentioning that the process/steps to put a node in maintenance mode were very similar to shutdown, with the exception of stopping the broker. Given that we aren't doing anything between "maintenance set" and "stop", I'm not sure if there is added value in putting the node in maintenance just before we stop it. 

What improvement would you like to get by implementing this issue?

**Comment by coro** [comment]
I asked the core team about this in Slack. The one aspect of maintenance mode that is not handled by just stopping the rabbitmq server process is:

> Transfer quorum queue leaders to other nodes. We will do this by shutting all Ra instances on this node down: this will trigger leader elections for quorum queues which target node won't participate in

To paraphrase @michaelklishin, by putting a node in maintenance mode before stopping it, we allow for more predictable responsibility transfer to other nodes. Other nodes would know that this cluster member should not be considered for queue leader placement, and perhaps more things in the future, if maintenance mode is extended in the future.

Copy-pasting our conclusion of what we should do:

Whenever a pod goes down (due to cluster rolling upgrade, or just restarting pods to apply a config change), we can (in this order):

- Wait for `rabbitmq-upgrade await_online_quorum_plus_one` and `rabbitmq-upgrade await_online_synchronized_mirror`
- Set the node to maintenance mode with `rabbitmq-upgrade drain`
- Allow the container runtime to send SIGTERM to rabbitmq-server
- Wait for the node to come back up and pass its readiness check (at which point 'maintenance' status is reset automatically, and it rejoins the cluster)
