### ISSUE TITLE
Do we still need the upgrade pipeline?

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#322]
**Is your feature request related to a problem? Please describe.**
Do we still need[ upgrade pipeline](https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator?group=upgrade)? Take a look of the postgres data that we have been collecting, if there is any interesting learnings or should we get rid of the pipeline instead.

**Comment by coro** [comment]
From what I can tell, the upgrade pipeline has failed since `2020-05-27@10:45:54+0000`, build [1607](https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/upgrade/builds/1607).

The [previous run](https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator/jobs/upgrade/builds/1606) lasted 5 days, and was the last to 'succeed'.

**Comment by coro** [comment]
We decided in sync up this morning that the pipeline in its current state is not useful, as it requires long-term maintenance of a compatible environment, and would not provide sufficient data for issues like #90 without modification.

We should therefore delete the pipeline, remove the pipeline definition, and remove Maven/Java from our CI image to save space.
