### ISSUE TITLE
deploying pods by statefulset fails on OpenShift 4.5.16

### ISSUE THREAD

**Issue by gnu300** [rabbitmq/cluster-operator#435]
## Describe the bug
After the deployment of the cluster-operator on OpenShift the statefulset can not create pods because of security constraints. Yes, i did change the scc annotation of the namespace according to the documentation to:
`    openshift.io/sa.scc.supplemental-groups: 999/1
     openshift.io/sa.scc.uid-range: 999/1
` 

## To Reproduce
After going through the setup process using:

1. https://www.rabbitmq.com/kubernetes/operator/install-operator.html
2. https://www.rabbitmq.com/kubernetes/operator/install-operator.html#openshift
3. https://www.rabbitmq.com/kubernetes/operator/using-operator.html

i created a cluster instance with:

`apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
spec:
  persistence:
   storageClassName: iscsi-block
   storage: 1Gi
  replicas: 1`

after that i get the following error from the statefulset controller:

`create Pod definition-rabbitmq-server-0 in StatefulSet definition-rabbitmq-server failed error: pods "definition-rabbitmq-server-0" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "persistentVolumeClaim": persistentVolumeClaim volumes are not allowed to be used spec.volumes[1]: Invalid value: "configMap": configMap volumes are not allowed to be used spec.volumes[2]: Invalid value: "configMap": configMap volumes are not allowed to be used spec.volumes[3]: Invalid value: "projected": projected volumes are not allowed to be used spec.volumes[4]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used spec.volumes[6]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used spec.volumes[7]: Invalid value: "downwardAPI": downwardAPI volumes are not allowed to be used spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be: 101 capabilities.add: Invalid value: "CHOWN": capability may not be added capabilities.add: Invalid value: "FOWNER": capability may not be added spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 999: must be: 101 spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [999, 999] capabilities.add: Invalid value: "CHOWN": capability may not be added capabilities.add: Invalid value: "FOWNER": capability may not be added]`

**Expected behavior**
I expect that the rabbitmq instance pod is created and that there are no security constraints or failures.

## Screenshots
Not applicable.

## Version information
- RabbitMQ: rabbitmq:3.8.9
- RabbitMQ Cluster Operator: 0.48.0
- Kubernetes: v1.18.3+2fbd7c7
- OpenShift 4.5.16
 
## Additional context
Not applicable.

**Comment by michaelklishin** [comment]
How can this be reproduced, step by step? You have provided no evidence to conclude that this is something that the Operator causes and not due to how security contexts are configured in your OpenShift installation.

**Comment by jbcodeforce** [comment]
I have the same issue since last week. So to reproduce: 
- deploy the cluster operator in the rabbitmq-system namespace with annotation:
`apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/name: rabbitmq-system
    app.kubernetes.io/part-of: rabbitmq
  annotations:
    openshift.io/sa.scc.supplemental-groups: 1000/1
    openshift.io/sa.scc.uid-range: 1000/1
  name: rabbitmq-system`
- create another namespace: rabbitmq-cluster with the annotation
`apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-cluster
  annotations:
    openshift.io/sa.scc.supplemental-groups: 999/1
    openshift.io/sa.scc.uid-range: 999/1
 `
- then deploy a cluster with 1 replicas. The error is that :

`create Pod jb-rmqcluster-rabbitmq-server-0 in StatefulSet jb-rmqcluster-rabbitmq-server failed error: pods "jb-rmqcluster-rabbitmq-server-0" is forbidden: unable to validate against any security context constraint: [spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [999, 999] capabilities.add: Invalid value: "CHOWN": capability may not be added capabilities.add: Invalid value: "FOWNER": capability may not be added]`

Which when looking to the generated stateful set yaml file there is a runAsUser 0 for the initContainer settings. 
spec:
      restartPolicy: Always
      initContainers:
        - resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          name: setup-container
          command:
            - sh
            - '-c'
            - >-
              cp /tmp/erlang-cookie-secret/.erlang.cookie
              /var/lib/rabbitmq/.erlang.cookie && chown 999:999
              /var/lib/rabbitmq/.erlang.cookie && chmod 600
              /var/lib/rabbitmq/.erlang.cookie ; cp
              /tmp/rabbitmq-plugins/enabled_plugins /operator/enabled_plugins &&
              chown 999:999 /operator/enabled_plugins ; chgrp 999
              /var/lib/rabbitmq/mnesia/
          securityContext:
            capabilities:
              add:
                - CHOWN
                - FOWNER
              drop:
                - ALL
            runAsUser: 0

Thank you

**Comment by ansd** [comment]
Thanks for reporting this issue @gnu300 @jbcodeforce.

@Zerpet and I could re-produce it when creating a new namespace in OpenShift. (However, the docs worked fine when creating the RabbitMQ cluster in the `default` namespace.)

Could you please test with the new doc changes in https://github.com/rabbitmq/rabbitmq-website/pull/1081 and give us feedback whether it works for you? These new docs work for us when running OpenShift locally in CRC.

The new docs assume that the service account in https://github.com/rabbitmq/rabbitmq-website/pull/1081/files#diff-a2b63bad52c1f68a3ee3ae1bd38d9bdf87ebe7ed27b42a148fe281944845788aR232 has the same name as the RabbitMQ cluster because https://github.com/rabbitmq/cluster-operator/pull/431 will soon be merged and released. For your tests, make sure to use the old name of the service account with the suffix `-rabbitmq-server` which would correspond in the example to:
`oc adm policy add-scc-to-user rabbitmq-cluster -z my-rabbitmq-rabbitmq-server`.

**Comment by jbcodeforce** [comment]
Hi, I did define the Security Constraints: as 
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: rabbitmq-cluster
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
requiredDropCapabilities:
  - "ALL"
allowedCapabilities:
  - "FOWNER"
  - "CHOWN"
volumes:
  - "configMap"
  - "secret"
  - "persistentVolumeClaim"
  - "downwardAPI"
  - "emptyDir"
  - "projected"

Then delete and redefine a new cluster called `rmqcluster` under the rabbitmq-cluster namespace. I did add the policy with: `oc adm policy add-scc-to-user rabbitmq-cluster -z rmqcluster`.  But I'm still getting the error:

`create Pod rmqcluster-rabbitmq-server-0 in StatefulSet rmqcluster-rabbitmq-server failed error: pods "rmqcluster-rabbitmq-server-0" is forbidden: unable to validate against any security context constraint: [spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [999, 999] capabilities.add: Invalid value: "CHOWN": capability may not be added capabilities.add: Invalid value: "FOWNER": capability may not be added]`
Thank you

**Comment by ansd** [comment]
@jbcodeforce did you also change the annotation `openshift.io/sa.scc.uid-range` in the rabbitmq-cluster namespace from `999` to `0-999` as described in https://github.com/rabbitmq/rabbitmq-website/pull/1081/files#diff-a2b63bad52c1f68a3ee3ae1bd38d9bdf87ebe7ed27b42a148fe281944845788aR227?

**Comment by jbcodeforce** [comment]
Yes I did change that now but now get another error: `create Pod rmqcluster-rabbitmq-server-0 in StatefulSet rmqcluster-rabbitmq-server failed error: pods "rmqcluster-rabbitmq-server-0" is forbidden: unable to validate against any security context constraint: [capabilities.add: Invalid value: "CHOWN": capability may not be added capabilities.add: Invalid value: "FOWNER": capability may not be added]`
the service account is named: rmqcluster-rabbitmq-server in my case, so should the scc be set for this user? 
thank you for your quick support anyway. Super!

**Comment by ansd** [comment]
Exactly, in your case the Security Context Constraint needs to be assigned to `rmqcluster-rabbitmq-server` because you're running operator version `0.48.0` or earlier. (There was a renaming done in https://github.com/rabbitmq/cluster-operator/pull/447 which is merged into `main` branch.)
Thanks for testing!

**Comment by jbcodeforce** [comment]
I validated, using good user works fine. So problem fixed. Thank you again for your support.
