### ISSUE TITLE
Close non-TLS service and container ports when `listeners.tcp = none` is set in the `rabbitmq.conf` configmap

### ISSUE THREAD

**Issue by ferozjilla** [rabbitmq/cluster-operator#459]
**Is your feature request related to a problem? Please describe.**
Users may [disable non-TLS listeners](https://www.rabbitmq.com/networking.html#single-stack-ipv4) by adding the `listeners.tcp = none` property to the [additional config](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#additional-config). This will result in the property being added to `rabbitmq.conf` which will result RabbitMQ not listening over non-TLS ports . The service and RabbitMQ container however will still expose the ports. This may be confusing for users and they may wonder if their intended change - disable non-TLS for RabbitMQ, has actually worked.

**Implementation Options**
1. The `rabbitmq.conf` configmap can detect when the property (`listeners.tcp = none`) is being set. If being set, we should remove all non-TLS ports from the service and the statefulset pod spec. Our resources do not have a way to affect each other at the moment, so we will have to figure out how to do this.

2. An alternative would be to add a top level property to the custom resource (something like `disableNonTLSListeners: true`). This would make it easy to identify when to change all affected objects (`rabbitmq.conf` configmap, service ports, container ports).

**Comment by ansd** [comment]
I vote for implementation option 2 because
1. It simplifies user experience: They set one single flag in the CR TLS spec and TLS will be enforced. Otherwise they would not only need to set `listeners.tcp = none`, but would also need to set `rabbitmq_web_stomp.tcp_config = none` and `rabbitmq_web_mqtt.tcp_config = none` if these plugins are enabled.
1. Users won't be surprised that service and container ports get modified because of rabbitmq.conf changes.
1. It simplifies controller logic. Not only would we need to check for `listeners.tcp = none` but also for `listeners.tcp = []`, `rabbitmq_web_stomp.tcp_config = none`, `rabbitmq_web_stomp.tcp_config = []`, `rabbitmq_web_mqtt.tcp_config = none`, `rabbitmq_web_mqtt.tcp_config = []` and branch differently based on whether TLS is enforced for STOMP-over-WebSockets, but not for MQTT-over-WebSockets and so on.
1. Such a flag has been proven to be successful in Cloud Foundry (see https://github.com/pivotal-cf/cf-rabbitmq-release/blob/f3bfc93765b8da0ae1355454d53fd2cf5f6dedef/jobs/rabbitmq-server/spec#L39-L41).

I think this issue is not a v1.0 blocker. We can add that field without any breaking change in the future.

**Comment by ferozjilla** [comment]
Option 2 will make the change backwards compatible since it only adds a new field to the CR while preserving existing behaviour without the field being there. 
I agree with all the points above and prefer option 2 too.
Thanks for listing them succinctly @ansd :)

**Comment by Zerpet** [comment]
> Such a flag has been proven to be successful in Cloud Foundry

This seems reason enough to me to choose option 2. Assuming that default value will behave as if this feature had not been implemented i.e. do not disable TLS ports by default. The reason being that setting default behaviour to remove TLS listeners would change the definition of the StatefulSet pod template upon upgrade, causing a rolling restart after upgrading the Operator.

**Comment by ChunyiLyu** [comment]
The team is happy with option 2 where we feature gate this feature. I've removed the high priority tag and the GA milestone. This is not a blocker anymore for `1.0` since it does not involve a change of behavior.

**Comment by ChunyiLyu** [comment]
One complication with this feature. After we disable no tls listeners, our tcp readiness probe will fail because it can no longer ping the amqp port. As part of disable tls listens, we also need to change the tcp probe to use amqps instead.

**Comment by mkuratczyk** [comment]
I don't understand the problem - if we have a property to disable non-TLS listeners then we can also change the probe to use `5671` instead. Why wouldn't that work?
