### ISSUE TITLE
Implement regression checking of documented examples

### ISSUE THREAD

**Issue by coro** [rabbitmq/cluster-operator#467]
**Is your feature request related to a problem? Please describe.**
In the docs directory of this repo, we provide a list of example manifests for various features, e.g. mTLS. The form of these manifests are validated in the upgrade pipeline, but there is no automated checking that the manifests deploy a RabbitMQ that does what the example intends. There is no guarantee that the examples displayed will work for all future Kubernetes server versions, or operator versions.

**Describe the solution you'd like**
We should create a framework that all of the examples can use to verify they function across supported K8s versions in the operator CI. This could just be a YAML containing instructions to deploy the example in kind and checks to run.

**Comment by ferozjilla** [comment]
We can add a `docs tests` tab in our [operator concourse pipeline](https://hush-house.pivotal.io/teams/rabbitmq-for-kubernetes/pipelines/operator).

Herein, we can can create the framework that tests the examples. For each docs example:
- deploy a KIND cluster (we can further iterate on supported k8s versions here)
- deploy the latest version of the operator
- `kubectl apply -f` the example yaml files
- ensure from the status conditions that the cluster is up and healthy
- test whether the example yaml had the expected result

All but the last step above is common for all examples. For the last step, each example can include a `test.sh` that takes in k8s cluster source credentials as input, and checks whether the example had the desired effect. This will then also help people that are following the docs to test the example had the desired effect. 

Thoughts? @coro

**Comment by coro** [comment]
Sounds great @ferozjilla ! The only one I can think of that might be an issue is the production ready example - given it uses an SSD storage class, and the incantation to create that is IaaS-specific, the example given is only for GKE and probably won't work on kind.

**Comment by Zerpet** [comment]
I'm considering if checking that all status conditions are `True` is enough to consider the deployment a success. I don't want start testing RabbitMQ itself, or asserting on RabbitMQ state directly. What was the initial motivation to build this framework? Was there a false positive with just the dry-run of the examples?

**Comment by Zerpet** [comment]
## Proposal

I'm writing up here a proposal to implement this. The reason to write a proposal is due to the scope, amount of work and impact on current and future examples to be written up.

### Problem statement

Our examples are a set of configurations that we provide to our community with a specific configuration and expectations. Since it is the maintainers of this repo who owns these examples, we should ensure that our recommendation and promises are kept. At the moment, we have room for some cases to go unnoticed, which could result in unmet expectation or unkept promises.

### Proposed solution

Our examples should include a file `test.sh` to assert on the state of RabbitMQ to ensure that it delivers the promises and expectations set. Optionally, it might include a file `setup.sh` to do initial preparation before the test is executed.

These scripts will be executed in a CI pipeline using a fresh Kubernetes cluster. The pipeline jobs that will run the example's tests will guarantee:

- The script `setup.sh` is executed before `RabbitmqCluster` object is created.
- All Status conditions are `True` before the script `test.sh` is executed.

The jobs in the CI pipeline will expect the script `test.sh` to exit with code 0 is all assertions were successful; the script `test.sh` should exit with non-zero code if any test or assertion failed. The same is expected for `setup.sh`.

These jobs should not block a release or our pipeline from producing a binary. The reason for this is the complexity in determining the offender; in other words, sometimes the example's tests might fail because the examples are outdated; in some other cases, we may have introduced a behaviour that broke the example or expectations. Given the complexity in determining this, it should not block our pipeline from producing a binary. In the event that a release is published with a broken example, we can release a patch version, if the root cause was determined to be in the Operator code.

Special cases or specific implementation details:

- If an example has a file `.ci-skip`, it won't be executed in the CI and it won't fail the job.
- If an example does not have a `test.sh`, it will fail the pipeline job and an appropriate error will be printed.

Sometimes, the setup must be done after `RabbitmqCluster` object is created. Unless we already have an example with this requirement, this won't be possible in the first iteration of this work. In such case, we could add support for `post-setup.sh` to execute setup steps after `RabbitmqCluster` object is created and `ClusterAvailable` condition is `True`.

**Comment by Zerpet** [comment]
## Context

Testing TLS related examples requires some mechanism in place to generate certificates. We can simplify this by using Cert Manager. 

Testing federation can be simplified by setting up federation within the same cluster between two different vhosts. It's going to be a bit tricky to assert success on this test because the CLI `rabbitmqadmin` returns 0 if we try to consume from an empty queue.

The tolerations example could be tested by taining *all* the nodes with `NoSchedule` and asserting that RabbitMQ deploys. This, however, gives me a bad feeling; I think we could somehow break the cluster.
