### ISSUE TITLE
when destroy definition and redeploy not take previous pv but create another 

### ISSUE THREAD

**Issue by ahmedfarouk1414** [rabbitmq/cluster-operator#508]
i deploy operator 
kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"
and create cluster definition 
###############################
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
spec:
  persistence:
   storageClassName: managed-nfs-storage
   storage: 20Gi
  service:
    type: NodePort
#############################3
when i destroy all and recreate definition again that create new pvc and pv 
i want to take the previous pv that contain my configration

**Comment by mkuratczyk** [comment]
Hi. The reason PVs are deleted and then recreated is due to [`reclaimPolicy` on your `storageClass`](https://kubernetes.io/docs/concepts/storage/storage-classes/#reclaim-policy). If you set `reclaimPolicy: retain` then PVs will not be deleted when you delete a `RabbitmqCluster`. However, if you delete RabbitMQ and create it again, new PVCs and PVs will be created (but the old PVs will still be around).

Can you explain your use case? If you want to have a cluster with the current configuration then why do you delete it?
