### ISSUE TITLE
Support for AZ awareness when creating pods

### ISSUE THREAD

**Issue by yaronp68** [rabbitmq/cluster-operator#515]
A K8s StatefulSet spreads pods across nodes. However, from v19 k8s supports [PodTopologySpreadCOnstraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) .
This feature allows to control how Pods are spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains. This can help to achieve high availability as well as efficient resource utilization.
Using the topologykey the user can select the node label that will be used to distinguish the failure domains in the cluster

User who wants to use rabbitMQ H/A features such as quorum queues might want to use this feature with the operator in order to achieve the optimal spread of pods into failure domains

**Comment by ChunyiLyu** [comment]
We are setting a default at the moment, and for users who wish to modify the constraint they need to use override. We can expose Topology Spread Constraint as a top level crd property to make it easier for users to configure themselves.

**Comment by ChunyiLyu** [comment]
This issue is about exposing  [PodTopologySpreadConstraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) in top level CRD. It's unclear whether we need to expose the entire k8s object for configurations. Whoever picks this up can think about what fields are necessary for users to configure and whether it's easier for users to only expose certain fields rather than the whole object.

**Comment by coro** [comment]
I also feel we're breaking some expectations for some users with our current behaviour by setting our own defaults. As per [the k8s docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#cluster-level-default-constraints), it is possible to set cluster-wide defaults for these constraints, that are applied to pods if both of the following are true:

* It doesn't define any constraints in its .spec.topologySpreadConstraints.
* It belongs to a service, replication controller, replica set or stateful set.

That means if I have a cluster with some constraints set on a cluster scope currently, and I create a base RabbitmqCluster object with no config in the object spec, the pods created will ignore the cluster's set constraints.

One question is whether to expose the PodTopologySpreadConstraints with no default, or the defaults we currently have. No default would allow the cluster-wide defaults to come into effect, if they are set (some defaults are set from v1.20 onwards regardless). However, this would require a breaking change in the operator, as upgrading the operator would cause the PodSpec to change and behaviour to change, or would require a new API version to mitigate this.

Another is whether to expose part of, or all of, the PodTopologySpreadConstraints object. While we could expose only part of the object now, if the object were to gain fields in the future, we would have to make further changes to include them, rather than picking them up from the core API. If we're exposing some fields in the object, it feels like relatively low effort to just expose the whole object instead, rather than cherry-picking the required fields.
