### ISSUE TITLE
Operator does not upgrade rabbitmq version

### ISSUE THREAD

**Issue by antoineozenne** [rabbitmq/cluster-operator#712]
## Describe the bug
When upgrading operator from 1.5.0 to 1.7.0, the rolling update doesn't upgrade the rabbitmq version (the image in the spec of deployed `RabbitmqCluster`).

## To Reproduce
1. Install the operator 1.5.0: `kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/download/v1.5.0/cluster-operator.yml"`
2. Deploy a `RabbitmqCluster` object, and verify the image in the spec is `rabbitmq:3.8.12-management`.
3. Upgrade to the operator 1.7.0: `kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/download/v1.7.0/cluster-operator.yml"`
4. See the image in the spec of the deployed `RabbitmqCluster` is `rabbitmq:3.8.12-management`.

**Expected behavior**
After the upgrade of the operator, I expect the image in the spec is `rabbitmq:3.8.16-management`.

## Version and environment information
- Helm: 3.5.3
- Kubernetes: 1.19.10

**Comment by Zerpet** [comment]
Hi there,

When we were designing the Operator, we wanted to provide as much data safety as possible, as well as flexible operation of RabbitMQ. Based on this design principle, we do not automatically change the spec of RabbitmqCluster objects, because this will cause a rolling restart of RabbitMQ Pods, which may not be desirable at the time you upgrade the Operator. Instead, we give the flexibility to choose when to upgrade your RabbitMQ instances, and to what version of RabbitMQ.

Looking at our documentation, I notice we don't have any section describing this, so I will take action to explain this behaviour in our docs.

**Comment by antoineozenne** [comment]
Thank you very much!
