### ISSUE TITLE
Node affinity conflict (node(s) had volume node affinity conflict)

### ISSUE THREAD

**Issue by rmtier** [rabbitmq/cluster-operator#726]
I am using AKS with rabbitmq operator. Using node affinity I am not able to properly set up rabbitmq cluster to proper node. I am using taint and tolerations plus node affinity and i am getting: 1 node(s) had volume node affinity conflict.

Persistent volume has not set proper node affinity, so i cant create own cluster on specific node.

**Comment by Zerpet** [comment]
Hey, can you share your RabbitmqCluster YAML manifest?

Node affinity should "hint" the scheduler that a Pod "prefers" a node, but it should not block scheduling, unless explicitly declared so.

**Comment by rmtier** [comment]
Can share but only partially, rigth now I was able to resove problem using storage class. Example:

`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rabbitmq
  namespace: prod
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: agentpool
    values:
    - rabbitmq`
    
   Node affitity is same on rabbit mq resource
   
   `apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
....
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "rabbitmq"
    effect: "NoSchedule"

  persistence:
    storageClassName: rabbitmq

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - rabbitmq
`
   
   Best woudt be if in documentation woudt be warning, or some kind of FAQ, or upper example.. https://www.rabbitmq.com/kubernetes/operator/using-operator.html

**Comment by Zerpet** [comment]
I tried to get the same situation in a GKE cluster with 3-nodes and the default storage classes, and I couldn't reproduce the issue. Does you AKS cluster have a default storage class?

I also have a suspicion that, perhaps, the persistent volume claim allocated a PV in a node that didn't match the affinity rules of RabbitMQ Pods (unlucky coincidence), and therefore I didn't see this behaviour in my cluster, because it was a simple 3-node kubernetes cluster, and chances of having this unlucky coincidene are much lower. Can you share the number of nodes in your Kubernetes cluster?
Are the nodes distributed between different regions or availability zones?
