### ISSUE TITLE
The CustomResourceDefinition in the manifest contains a read-only field

### ISSUE THREAD

**Issue by sambonbonne** [rabbitmq/cluster-operator#761]
## Describe the bug

The `status` field at the root of Kubernetes resources is read-only but the CustomResourceDefinition in RabbitMQ cluster operator manifest contains this field (with empty values).

For example, in the `1.8.0` manifest, line `4402`, we have:

```yaml
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

This field should not be provided by the manifest.

## To Reproduce

1. Download the cluster operator manifest (tested with `1.8.0`)
2. Edit it, go to the end of the `CustomResourceDefinition` declaration
3. See the `status` field is present

**Expected behavior**

The `status field` should not be here.

## Version and environment information
- RabbitMQ: 3.8.18 (set by operator but seem not applicable here)
- RabbitMQ Cluster Operator: 1.8.0
- Kubernetes: not applicable
- Cloud provider or hardware configuration: not applicable
 
## Additional context

I use a tool which takes yaml to convert to its own format, and the `status` field is not accepted as it is read-only in Kubernetes.

**Comment by ChunyiLyu** [comment]
The `status` field is generated by `controller-gen` which is the tool that the cluster operator uses for generating crd definitions. I found an issue in controller-gen that reflects the issue you are describing: https://github.com/kubernetes-sigs/controller-tools/issues/456. I don't think this is a bug because the CRD definition is not broken when applied directly to kubernetes. In the mean time, I recommend remove the status field in your own tool until the above issue is fixed inside https://github.com/kubernetes-sigs/controller-tools.

**Comment by sambonbonne** [comment]
Thanks for this highlight, I'll follow the upstream issue.

For now I'm already using the edited chart like you suggest, hoping the upstream issue will gain some interests from the maintainers.
