### ISSUE TITLE
Wrong prometheus scrape port with TLS enabled

### ISSUE THREAD

**Issue by kotyara85** [rabbitmq/cluster-operator#797]
operator version: 1.8.1

tlsEnabled
Annotations operator adds:
```
        prometheus.io/port: "15691"
        prometheus.io/scrape: "true"
```

prometheus is trying to scrape TLS port with http - `http://10.233.82.244:15691/metrics`

**Comment by mkuratczyk** [comment]
Back when we introduced these annotations, `prometheus.io/scheme` didn't exist. It seems like it exists now but at the same time, annotation-based approach has been discouraged by the Prometheus community, in favour of ServiceMonitor/PodMonitor: https://github.com/prometheus-operator/prometheus-operator/issues/1547#issuecomment-401092041. Because of that, rather than introducing yet another annotation, we are considering removing the annotations that already exist. Is there any reason why you want to rely on the annotations and not the approach we documented in https://www.rabbitmq.com/kubernetes/operator/operator-monitoring.html?
