### ISSUE TITLE
Remove Prometheus port from client service

### ISSUE THREAD

**Issue by st3v** [rabbitmq/cluster-operator#83]
**Is your feature request related to a problem? Please describe.**
We currently define a `prometheus` port on the client service for a given `RabbitmqCluster`. Having that port there is misleading. It suggests to have Prometheus scrape this service for metrics on the specified port. Due to its load-balancing nature, if a user scraps this service with Prometheus they will...
1. only get metrics for a single RabbitMQ node at any point in time and...
2. get potentially inconsistent and rapidly changing metrics as the service might redirect to two different RabbitMQ nodes on subsequent scrapes

**Describe the solution you'd like**
Remove the `prometheus` port from the service. Adapt our docs accordingly.

**Describe alternatives you've considered**
We could think about adding the `prometheus` port to the headless service which doesn't load-balance. Or alternatively, create additional client services, one for each RabbitMQ node. Such services would also be interesting for AMQP client-side load-balancing.

**Additional context**
n/a

**Comment by CrazyByDefault** [comment]
@j4mcs Hi, I was splitting hairs over why the inbuilt monitoring was not workin - Prometheus targets were showing the rabbitmq object, but showed a solid 0/0 targets discovered.  

It turns out that with recent kube-prometheus and the Prometheus Operator, adding the `prometheus` port to the rmq client service leads to natural discovery of underlying node IPs via the `ServiceMonitor` that is defined.  

In fact, the [default configuration](https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/prometheus/monitors/rabbitmq-servicemonitor.yml) for `ServiceMonitor` that is recommended [here](https://www.rabbitmq.com/kubernetes/operator/operator-monitoring.html) in the docs, looks for the `prometheus` port across all services, which is missing by default and had to be added in as so - 

```yaml
spec:
  replicas: 3
  override:
    service:
      spec:
        ports:
          - name: prometheus
            protocol: TCP
            port: 15692
```

Once I did this, the 3 replicas showed up immediately in the Prometheus targets. I believe this change will have to be communicated via the docs, or have the client service re-updated to include the port?
